// Milestone email #6 - fires when Trello card moves into
// "Awaiting Payment" or "Closed". The wrap-up + feedback survey
// email. Primary CTA is the feedback form (Phase 4 - feedback form
// itself will live at shoots.fame.so/feedback/<slug>, persisted to
// the shared Supabase project that backs delivery.fame.so).
//
// No timeline embed - post-shoot.

import { Text } from "@react-email/components";
import { EmailLayout, OutlineButton, PrimaryButton } from "../layout";
import { QuestionsCTA } from "../questions-cta";
import { fameTheme } from "../theme";
import type { Shoot } from "../../types";

const { colors } = fameTheme;

export type DeliveredProps = {
  shoot: Shoot;
  // /feedback/<slug> on the public domain. Generated by the caller
  // since the public base lives in env.
  feedbackUrl: string;
  // Status page (still live after delivery so the client can find
  // files later).
  statusPageUrl: string;
  clientFirstName: string;
};

export function DeliveredEmail({
  shoot,
  feedbackUrl,
  statusPageUrl,
  clientFirstName,
}: DeliveredProps) {
  const greeting = clientFirstName ? `Hi ${clientFirstName},` : "Hi there,";

  return (
    <EmailLayout
      preview={`How was your Fame shoot? - ${shoot.shootNumber} wrap-up`}
      hero={{
        shootNumber: shoot.shootNumber,
        title: shoot.clientName,
        statusLabel: "Delivered",
      }}
      signOffName={shoot.producerFirstName}
    >
      <Text style={lede}>How did we do?</Text>
      <Text style={paragraph}>{greeting}</Text>
      <Text style={paragraph}>
        That's a wrap on {shoot.shootNumber}. Thanks for working with
        Fame - it's been a pleasure.
      </Text>
      <Text style={paragraph}>
        Quick ask: 60 seconds to tell us how it went? Honest feedback
        (the good and the bad) is what helps us get better for the next
        one.
      </Text>

      <PrimaryButton href={feedbackUrl}>Share your feedback</PrimaryButton>

      <Text style={paragraph}>
        Your status page stays live with all the deliverables - bookmark
        it if you haven't already:
      </Text>

      <OutlineButton href={statusPageUrl}>Open your status page</OutlineButton>

      <QuestionsCTA whatsappUrl={shoot.clientWhatsappUrl} />
    </EmailLayout>
  );
}

const lede = {
  fontSize: "22px",
  fontWeight: 700,
  margin: "8px 0 16px",
  color: colors.dark,
  letterSpacing: "-0.01em",
};

const paragraph = {
  margin: "0 0 14px",
  color: colors.dark,
};
